global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:50051']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:50052']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:50053']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:50054']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:50055']

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:8014']

  - job_name: 'proxy-service'
    static_configs:
      - targets: ['proxy-service:8007']

  - job_name: 'sms-service'
    static_configs:
      - targets: ['sms-service:8008']

  - job_name: 'vk-service'
    static_configs:
      - targets: ['vk-service:8009']

  - job_name: 'telegram-service'
    static_configs:
      - targets: ['telegram-service:8010']

  - job_name: 'mail-service'
    static_configs:
      - targets: ['mail-service:8011']

  - job_name: 'max-service'
    static_configs:
      - targets: ['max-service:8012']